// Dane liczników (klasyfikatorów) japońskich.
// Każdy element ma: num (liczba), kanji (zapis liczby), reading (hiragana),
// romaji (tablica akceptowanych zapisów romaji, pierwszy jest "głównym").
// Kolejne warianty czytania to osobne elementy z tym samym "num".

const COUNTER_GROUPS = {
  people: {
    id: "people",
    label: "Osoby",
    counter: "人",
    reading: "nin / ~ri",
    color: "#e57373",
    items: [
      { num: 1, kanji: "一", reading: "ひとり", romaji: ["hitori"] },
      { num: 2, kanji: "二", reading: "ふたり", romaji: ["futari"] },
      { num: 3, kanji: "三", reading: "さんにん", romaji: ["sannin"] },
      { num: 4, kanji: "四", reading: "よにん", romaji: ["yonin"] },
      { num: 5, kanji: "五", reading: "ごにん", romaji: ["gonin"] },
      { num: 6, kanji: "六", reading: "ろくにん", romaji: ["rokunin"] },
      { num: 7, kanji: "七", reading: "しちにん", romaji: ["shichinin"] },
      { num: 7, kanji: "七", reading: "ななにん", romaji: ["nananin"] },
      { num: 8, kanji: "八", reading: "はちにん", romaji: ["hachinin"] },
      { num: 9, kanji: "九", reading: "きゅうにん", romaji: ["kyuunin", "kyunin"] },
      { num: 10, kanji: "十", reading: "じゅうにん", romaji: ["juunin", "junin"] },
      { num: "?", kanji: "何", reading: "なんにん", romaji: ["nannin"] }
    ]
  },

  minutes: {
    id: "minutes",
    label: "Minuty",
    counter: "分",
    reading: "fun / pun",
    color: "#64b5f6",
    items: [
      { num: 1, kanji: "一", reading: "いっぷん", romaji: ["ippun"] },
      { num: 2, kanji: "二", reading: "にふん", romaji: ["nifun"] },
      { num: 3, kanji: "三", reading: "さんぷん", romaji: ["sanpun"] },
      { num: 4, kanji: "四", reading: "よんぷん", romaji: ["yonpun"] },
      { num: 5, kanji: "五", reading: "ごふん", romaji: ["gofun"] },
      { num: 6, kanji: "六", reading: "ろっぷん", romaji: ["roppun"] },
      { num: 7, kanji: "七", reading: "ななふん", romaji: ["nanafun"] },
      { num: 8, kanji: "八", reading: "はっぷん", romaji: ["happun"] },
      { num: 8, kanji: "八", reading: "はちふん", romaji: ["hachifun"] },
      { num: 9, kanji: "九", reading: "きゅうふん", romaji: ["kyuufun", "kyufun"] },
      { num: 10, kanji: "十", reading: "じゅっぷん", romaji: ["juppun"] },
      { num: 10, kanji: "十", reading: "じっぷん", romaji: ["jippun"] },
      { num: 11, kanji: "十一", reading: "じゅういっぷん", romaji: ["juuippun"] },
      { num: 12, kanji: "十二", reading: "じゅうにふん", romaji: ["juunifun"] },
      { num: 13, kanji: "十三", reading: "じゅうさんぷん", romaji: ["juusanpun"] },
      { num: 14, kanji: "十四", reading: "じゅうよんぷん", romaji: ["juuyonpun"] },
      { num: 15, kanji: "十五", reading: "じゅうごふん", romaji: ["juugofun"] },
      { num: 16, kanji: "十六", reading: "じゅうろっぷん", romaji: ["juuroppun"] },
      { num: 17, kanji: "十七", reading: "じゅうななふん", romaji: ["juunanafun"] },
      { num: 18, kanji: "十八", reading: "じゅうはっぷん", romaji: ["juuhappun"] },
      { num: 19, kanji: "十九", reading: "じゅうきゅうふん", romaji: ["juukyuufun"] },
      { num: 20, kanji: "二十", reading: "にじゅっぷん", romaji: ["nijuppun", "nijippun"] },
      { num: 21, kanji: "二十一", reading: "にじゅういっぷん", romaji: ["nijuuippun"] },
      { num: 22, kanji: "二十二", reading: "にじゅうにふん", romaji: ["nijuunifun"] },
      { num: 23, kanji: "二十三", reading: "にじゅうさんぷん", romaji: ["nijuusanpun"] },
      { num: 24, kanji: "二十四", reading: "にじゅうよんぷん", romaji: ["nijuuyonpun"] },
      { num: 25, kanji: "二十五", reading: "にじゅうごふん", romaji: ["nijuugofun"] },
      { num: 26, kanji: "二十六", reading: "にじゅうろっぷん", romaji: ["nijuuroppun"] },
      { num: 27, kanji: "二十七", reading: "にじゅうななふん", romaji: ["nijuunanafun"] },
      { num: 28, kanji: "二十八", reading: "にじゅうはっぷん", romaji: ["nijuuhappun"] },
      { num: 29, kanji: "二十九", reading: "にじゅうきゅうふん", romaji: ["nijuukyuufun"] },
      { num: 30, kanji: "三十", reading: "さんじゅっぷん", romaji: ["sanjuppun", "sanjippun"] },
      { num: 31, kanji: "三十一", reading: "さんじゅういっぷん", romaji: ["sanjuuippun"] },
      { num: 32, kanji: "三十二", reading: "さんじゅうにふん", romaji: ["sanjuunifun"] },
      { num: 33, kanji: "三十三", reading: "さんじゅうさんぷん", romaji: ["sanjuusanpun"] },
      { num: 34, kanji: "三十四", reading: "さんじゅうよんぷん", romaji: ["sanjuuyonpun"] },
      { num: 35, kanji: "三十五", reading: "さんじゅうごふん", romaji: ["sanjuugofun"] },
      { num: 36, kanji: "三十六", reading: "さんじゅうろっぷん", romaji: ["sanjuuroppun"] },
      { num: 37, kanji: "三十七", reading: "さんじゅうななふん", romaji: ["sanjuunanafun"] },
      { num: 38, kanji: "三十八", reading: "さんじゅうはっぷん", romaji: ["sanjuuhappun"] },
      { num: 39, kanji: "三十九", reading: "さんじゅうきゅうふん", romaji: ["sanjuukyuufun"] },
      { num: 40, kanji: "四十", reading: "よんじゅっぷん", romaji: ["yonjuppun", "yonjippun"] },
      { num: 41, kanji: "四十一", reading: "よんじゅういっぷん", romaji: ["yonjuuippun"] },
      { num: 42, kanji: "四十二", reading: "よんじゅうにふん", romaji: ["yonjuunifun"] },
      { num: 43, kanji: "四十三", reading: "よんじゅうさんぷん", romaji: ["yonjuusanpun"] },
      { num: 44, kanji: "四十四", reading: "よんじゅうよんぷん", romaji: ["yonjuuyonpun"] },
      { num: 45, kanji: "四十五", reading: "よんじゅうごふん", romaji: ["yonjuugofun"] },
      { num: 46, kanji: "四十六", reading: "よんじゅうろっぷん", romaji: ["yonjuuroppun"] },
      { num: 47, kanji: "四十七", reading: "よんじゅうななふん", romaji: ["yonjuunanafun"] },
      { num: 48, kanji: "四十八", reading: "よんじゅうはっぷん", romaji: ["yonjuuhappun"] },
      { num: 49, kanji: "四十九", reading: "よんじゅうきゅうふん", romaji: ["yonjuukyuufun"] },
      { num: 50, kanji: "五十", reading: "ごじゅっぷん", romaji: ["gojuppun", "gojippun"] },
      { num: 51, kanji: "五十一", reading: "ごじゅういっぷん", romaji: ["gojuuippun"] },
      { num: 52, kanji: "五十二", reading: "ごじゅうにふん", romaji: ["gojuunifun"] },
      { num: 53, kanji: "五十三", reading: "ごじゅうさんぷん", romaji: ["gojuusanpun"] },
      { num: 54, kanji: "五十四", reading: "ごじゅうよんぷん", romaji: ["gojuuyonpun"] },
      { num: 55, kanji: "五十五", reading: "ごじゅうごふん", romaji: ["gojuugofun"] },
      { num: 56, kanji: "五十六", reading: "ごじゅうろっぷん", romaji: ["gojuuroppun"] },
      { num: 57, kanji: "五十七", reading: "ごじゅうななふん", romaji: ["gojuunanafun"] },
      { num: 58, kanji: "五十八", reading: "ごじゅうはっぷん", romaji: ["gojuuhappun"] },
      { num: 59, kanji: "五十九", reading: "ごじゅうきゅうふん", romaji: ["gojuukyuufun"] },
      { num: 60, kanji: "六十", reading: "ろくじゅっぷん", romaji: ["rokujuppun", "rokujippun"] },
      { num: "?", kanji: "何", reading: "なんぷん", romaji: ["nanpun"] }
    ]
  },

  hours: {
    id: "hours",
    label: "Godziny",
    counter: "時",
    reading: "ji",
    color: "#81c784",
    items: [
      { num: 1, kanji: "一", reading: "いちじ", romaji: ["ichiji"] },
      { num: 2, kanji: "二", reading: "にじ", romaji: ["niji"] },
      { num: 3, kanji: "三", reading: "さんじ", romaji: ["sanji"] },
      { num: 4, kanji: "四", reading: "よじ", romaji: ["yoji"] },
      { num: 5, kanji: "五", reading: "ごじ", romaji: ["goji"] },
      { num: 6, kanji: "六", reading: "ろくじ", romaji: ["rokuji"] },
      { num: 7, kanji: "七", reading: "しちじ", romaji: ["shichiji"] },
      { num: 8, kanji: "八", reading: "はちじ", romaji: ["hachiji"] },
      { num: 9, kanji: "九", reading: "くじ", romaji: ["kuji"] },
      { num: 10, kanji: "十", reading: "じゅうじ", romaji: ["juuji", "juji"] },
      { num: 11, kanji: "十一", reading: "じゅういちじ", romaji: ["juuichiji", "juichiji"] },
      { num: 12, kanji: "十二", reading: "じゅうにじ", romaji: ["juuniji", "juniji"] },
      { num: "?", kanji: "何", reading: "なんじ", romaji: ["nanji"] }
    ]
  },

  days: {
    id: "days",
    label: "Dni",
    counter: "日",
    reading: "nichi / ~ka",
    color: "#ba68c8",
    items: [
      { num: 1, kanji: "一", reading: "ついたち", romaji: ["tsuitachi"] },
      { num: 2, kanji: "二", reading: "ふつか", romaji: ["futsuka"] },
      { num: 3, kanji: "三", reading: "みっか", romaji: ["mikka"] },
      { num: 4, kanji: "四", reading: "よっか", romaji: ["yokka"] },
      { num: 5, kanji: "五", reading: "いつか", romaji: ["itsuka"] },
      { num: 6, kanji: "六", reading: "むいか", romaji: ["muika"] },
      { num: 7, kanji: "七", reading: "なのか", romaji: ["nanoka"] },
      { num: 8, kanji: "八", reading: "ようか", romaji: ["youka", "yoka"] },
      { num: 9, kanji: "九", reading: "ここのか", romaji: ["kokonoka"] },
      { num: 10, kanji: "十", reading: "とおか", romaji: ["tooka", "toka"] },
      { num: 11, kanji: "十一", reading: "じゅういちにち", romaji: ["juuichinichi"] },
      { num: 12, kanji: "十二", reading: "じゅうににち", romaji: ["juuninichi"] },
      { num: 13, kanji: "十三", reading: "じゅうさんにち", romaji: ["juusannichi"] },
      { num: 14, kanji: "十四", reading: "じゅうよっか", romaji: ["juuyokka", "juyokka"] },
      { num: 15, kanji: "十五", reading: "じゅうごにち", romaji: ["juugonichi"] },
      { num: 16, kanji: "十六", reading: "じゅうろくにち", romaji: ["juurokunichi"] },
      { num: 17, kanji: "十七", reading: "じゅうしちにち", romaji: ["juushichinichi", "juunananichi"] },
      { num: 18, kanji: "十八", reading: "じゅうはちにち", romaji: ["juuhachinichi"] },
      { num: 19, kanji: "十九", reading: "じゅうくにち", romaji: ["juukunichi"] },
      { num: 20, kanji: "二十", reading: "はつか", romaji: ["hatsuka"] },
      { num: 21, kanji: "二十一", reading: "にじゅういちにち", romaji: ["nijuuichinichi"] },
      { num: 22, kanji: "二十二", reading: "にじゅうににち", romaji: ["nijuuninichi"] },
      { num: 23, kanji: "二十三", reading: "にじゅうさんにち", romaji: ["nijuusannichi"] },
      { num: 24, kanji: "二十四", reading: "にじゅうよっか", romaji: ["nijuuyokka", "nijuyokka"] },
      { num: 25, kanji: "二十五", reading: "にじゅうごにち", romaji: ["nijuugonichi"] },
      { num: 26, kanji: "二十六", reading: "にじゅうろくにち", romaji: ["nijuurokunichi"] },
      { num: 27, kanji: "二十七", reading: "にじゅうしちにち", romaji: ["nijuushichinichi", "nijuunananichi"] },
      { num: 28, kanji: "二十八", reading: "にじゅうはちにち", romaji: ["nijuuhachinichi"] },
      { num: 29, kanji: "二十九", reading: "にじゅうくにち", romaji: ["nijuukunichi"] },
      { num: 30, kanji: "三十", reading: "さんじゅうにち", romaji: ["sanjuunichi"] },
      { num: 31, kanji: "三十一", reading: "さんじゅういちにち", romaji: ["sanjuuichinichi"] },
      { num: "?", kanji: "何", reading: "なんにち", romaji: ["nannichi"] }
    ]
  },

  things: {
    id: "things",
    label: "Przedmioty (ogólny)",
    counter: "つ",
    reading: "~tsu",
    color: "#ffb74d",
    items: [
      { num: 1, kanji: "一", reading: "ひとつ", romaji: ["hitotsu"] },
      { num: 2, kanji: "二", reading: "ふたつ", romaji: ["futatsu"] },
      { num: 3, kanji: "三", reading: "みっつ", romaji: ["mittsu"] },
      { num: 4, kanji: "四", reading: "よっつ", romaji: ["yottsu"] },
      { num: 5, kanji: "五", reading: "いつつ", romaji: ["itsutsu"] },
      { num: 6, kanji: "六", reading: "むっつ", romaji: ["muttsu"] },
      { num: 7, kanji: "七", reading: "ななつ", romaji: ["nanatsu"] },
      { num: 8, kanji: "八", reading: "やっつ", romaji: ["yattsu"] },
      { num: 9, kanji: "九", reading: "ここのつ", romaji: ["kokonotsu"] },
      // 10 zapisuje się samym 十 (とお), bez つ
      { num: 10, kanji: "十", label: "十", reading: "とお", romaji: ["too", "to"] },
      // forma pytająca to いくつ (幾つ), a nie なんつ
      { num: "?", kanji: "幾", label: "幾つ", reading: "いくつ", romaji: ["ikutsu"] }
    ]
  },

  animals: {
    id: "animals",
    label: "Małe zwierzęta",
    counter: "匹",
    reading: "hiki / piki / biki",
    color: "#4db6ac",
    items: [
      { num: 1, kanji: "一", reading: "いっぴき", romaji: ["ippiki"] },
      { num: 2, kanji: "二", reading: "にひき", romaji: ["nihiki"] },
      { num: 3, kanji: "三", reading: "さんびき", romaji: ["sanbiki"] },
      { num: 4, kanji: "四", reading: "よんひき", romaji: ["yonhiki"] },
      { num: 5, kanji: "五", reading: "ごひき", romaji: ["gohiki"] },
      { num: 6, kanji: "六", reading: "ろっぴき", romaji: ["roppiki"] },
      { num: 7, kanji: "七", reading: "ななひき", romaji: ["nanahiki"] },
      { num: 8, kanji: "八", reading: "はっぴき", romaji: ["happiki"] },
      { num: 9, kanji: "九", reading: "きゅうひき", romaji: ["kyuuhiki"] },
      { num: 10, kanji: "十", reading: "じゅっぴき", romaji: ["juppiki", "jippiki"] },
      { num: "?", kanji: "何", reading: "なんびき", romaji: ["nanbiki"] }
    ]
  }
};
